version: '2'
services:
 client:
  build: projet-webservice
  ports:
   - "4200:4200"

 express:
  build: express-server
  ports:
   - "3000:3000"
  links:
   - redis

 redis:
  image: redis
  ports:
   - "6379:6379"

 protractor:
  build: protractor
